// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ALM_GMD
Rcpp::List ALM_GMD(arma::vec y, arma::mat Z, arma::mat Zc, arma::mat Zc_proj, arma::vec beta, arma::vec lambda, arma::vec pf, int dfmax, int pfmax, arma::mat A, arma::vec b, arma::umat group_index, int inner_maxiter, int outer_maxiter, double inner_eps, double outer_eps, double mu_ratio, double u_ini, double tol);
RcppExport SEXP _compReg_ALM_GMD(SEXP ySEXP, SEXP ZSEXP, SEXP ZcSEXP, SEXP Zc_projSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP pfSEXP, SEXP dfmaxSEXP, SEXP pfmaxSEXP, SEXP ASEXP, SEXP bSEXP, SEXP group_indexSEXP, SEXP inner_maxiterSEXP, SEXP outer_maxiterSEXP, SEXP inner_epsSEXP, SEXP outer_epsSEXP, SEXP mu_ratioSEXP, SEXP u_iniSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc(ZcSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc_proj(Zc_projSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pfmax(pfmaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type group_index(group_indexSEXP);
    Rcpp::traits::input_parameter< int >::type inner_maxiter(inner_maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type outer_maxiter(outer_maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type inner_eps(inner_epsSEXP);
    Rcpp::traits::input_parameter< double >::type outer_eps(outer_epsSEXP);
    Rcpp::traits::input_parameter< double >::type mu_ratio(mu_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type u_ini(u_iniSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(ALM_GMD(y, Z, Zc, Zc_proj, beta, lambda, pf, dfmax, pfmax, A, b, group_index, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol));
    return rcpp_result_gen;
END_RCPP
}
// ALM_BG
Rcpp::List ALM_BG(arma::vec y, arma::mat Z, arma::mat Zc, arma::mat Zc_proj, arma::vec beta, arma::vec lambda, arma::vec pf, double b, arma::vec A, int dfmax, int pfmax, int inner_maxiter, int outer_maxiter, double inner_eps, double outer_eps, double mu_ratio, double u_ini, double tol);
RcppExport SEXP _compReg_ALM_BG(SEXP ySEXP, SEXP ZSEXP, SEXP ZcSEXP, SEXP Zc_projSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP pfSEXP, SEXP bSEXP, SEXP ASEXP, SEXP dfmaxSEXP, SEXP pfmaxSEXP, SEXP inner_maxiterSEXP, SEXP outer_maxiterSEXP, SEXP inner_epsSEXP, SEXP outer_epsSEXP, SEXP mu_ratioSEXP, SEXP u_iniSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc(ZcSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc_proj(Zc_projSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pfmax(pfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type inner_maxiter(inner_maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type outer_maxiter(outer_maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type inner_eps(inner_epsSEXP);
    Rcpp::traits::input_parameter< double >::type outer_eps(outer_epsSEXP);
    Rcpp::traits::input_parameter< double >::type mu_ratio(mu_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type u_ini(u_iniSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(ALM_BG(y, Z, Zc, Zc_proj, beta, lambda, pf, b, A, dfmax, pfmax, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol));
    return rcpp_result_gen;
END_RCPP
}
// ALM_B
Rcpp::List ALM_B(arma::vec y, arma::mat Z, arma::mat Zc, arma::mat Zc_proj, arma::vec beta, arma::vec lambda, arma::vec pf, int dfmax, int pfmax, int inner_maxiter, int outer_maxiter, double inner_eps, double outer_eps, double mu_ratio, double u_ini, double tol);
RcppExport SEXP _compReg_ALM_B(SEXP ySEXP, SEXP ZSEXP, SEXP ZcSEXP, SEXP Zc_projSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP pfSEXP, SEXP dfmaxSEXP, SEXP pfmaxSEXP, SEXP inner_maxiterSEXP, SEXP outer_maxiterSEXP, SEXP inner_epsSEXP, SEXP outer_epsSEXP, SEXP mu_ratioSEXP, SEXP u_iniSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc(ZcSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc_proj(Zc_projSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pfmax(pfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type inner_maxiter(inner_maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type outer_maxiter(outer_maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type inner_eps(inner_epsSEXP);
    Rcpp::traits::input_parameter< double >::type outer_eps(outer_epsSEXP);
    Rcpp::traits::input_parameter< double >::type mu_ratio(mu_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type u_ini(u_iniSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(ALM_B(y, Z, Zc, Zc_proj, beta, lambda, pf, dfmax, pfmax, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_compReg_ALM_GMD", (DL_FUNC) &_compReg_ALM_GMD, 19},
    {"_compReg_ALM_BG", (DL_FUNC) &_compReg_ALM_BG, 18},
    {"_compReg_ALM_B", (DL_FUNC) &_compReg_ALM_B, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_compReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
